### ISSUE TITLE
Detect environment variable

### ISSUE THREAD

**Issue by craigdallimore** [3v0k4/exit.nvim#2]
Neat idea for a plugin! It's a little tricky to search for it though :)

It would be great if the plugin could detect an `$OPENAI_API_KEY` environment variable, similar to how https://github.com/jackMort/ChatGPT.nvim does it.

**Comment by 3v0k4** [comment]
Thanks for the good words, @craigdallimore.

Is this preventing you from using the plugin? Could you please let me know why you would prefer to use the ENV instead of the current behavior (API keys for LLMs saved in either "$XDG_DATA_HOME/exit.nvim" or "$HOME/.local/share/exit.nvim")?

I just want to understand better where you are coming from to see what's the best plan of action 🙂

**Comment by craigdallimore** [comment]
> Could you please let me know why you would prefer to use the ENV instead of the current behavior (API keys for LLMs saved in either "$XDG_DATA_HOME/exit.nvim" or "$HOME/.local/share/exit.nvim")?

I prefer not to store keys in cleartext; I share my configs in a remote repository and I figure it's a good practice not to commit keys. Instead I use [age](https://github.com/FiloSottile/age) to generate the keys. 

This might not need a change to exit.nvim though, I could probably figure out a way to inject them into my nvim config dynamically. Happy to close this one.

**Comment by craigdallimore** [comment]
Oh, I see how it works now. The plugin will prompt for the key then store it in cleartext at `$HOME/.local/share/exit.nvim`.

**Comment by 3v0k4** [comment]
Thanks for the clarification 🙏

Also, thanks for making me aware of age, TIL!

**Comment by craigdallimore** [comment]
Thanks for the great plugin. It's great for handling things like "put the
path to this file in the clipboard" which I would have to look up
